const Data = [
  {
    id: "1",
    title: "Typical day of Data Scientist - An insider story!",
    category: "Artificial Intelligence",
    name: "Saurav Ghosh",
    dated: "05 Jul 2019",
    img: "https://edyoda.s3.amazonaws.com/media/blog-images/Data_Scientist_1920_1280_DsZBGZu.jpg",
    desc: "I’ve been a Data Scientist for three years now and I can only say that Chris Lynch was right - Big Data and Data Science are the foundation of all the trends that are emerging in the world today. To me Data Science can be encapsulated in a simple statement, it helps organizations and individuals to solve complex problems while minimizing human effort. There are several different aspects to this, which we shall go into later.",
  },
  {
    id: "2",
    title: "Amazon Web Services (AWS) Cloud Day - Bangalore",
    category: "Cloud Computing",
    name: "Kalyan Mahalingam",
    dated: "05 Jul 2019",
    img: "https://edyoda.s3.amazonaws.com/media/blog-images/edyoda_blog_aws_cloudday_17may2018_Bangalore_small_ByulIE.jpg",
    desc: "It was indeed a hectic day with back to back session sandwiched by good food and tea (on a lighter note, need to investigate the tactics behind the 5-star hotels keeping the plates so heavy. :D) To me, AWS cloud day gave a lot of insights into the Business I am into -  Consulting & Training for Cloud & DevOps, and I could comprehend from the various sessions I attended, the way AWS and its business partners are moving.",
  },
  {
    id: "3",
    title: "From identity crisis to the Success Story - The DevOps revolution!",
    category: "DevOps",
    name: "Kalyan Mahalingam",
    dated: "05 Jul 2019",
    img: "https://edyoda.s3.amazonaws.com/media/blog-images/devops-edYoda-blog-small.jpg",
    desc: "DevOps is a paradigm shift in the way how software products are being built in the modern day Information Technology (IT) organizations. It is becoming the de-facto component in Software Development Lifecycle (SDLC) process in most of the organizations.",
  },
  {
    id: "4",
    title: "Learn these Programming Languages in 2019",
    category: "Programming Languages",
    name: "EdYoda",
    dated: "08 Jul 2019",
    img: "https://edyoda.s3.amazonaws.com/media/blog-images/WhatsApp_Image_2019-06-19_at_17.55.10.jpeg",
    desc: "Starting a career as a software developer obviously requires one to undertake a programming languages course that can cover everything from the basics to even the minute details. To learn a programming language though, one needs to also understand which one is suitable for you. Once your journey as a developer starts you will soon understand which language will be the most suited to you, your interests and career goals.",
  },
  {
    id: "5",
    title: "Why you should accelerate your knowledge on Mobile App Development",
    category: "Mobile Application Development",
    name: "EdYoda",
    dated: "23 Jul 2019",
    img: "https://edyoda.s3.amazonaws.com/media/blog-images/why-you-should-accelerate-your-knowledge-on-mobile-app-development.jpg",
    desc: "Over the most recent 10 years, Android has become famous, not only with its themes that have candy names yet in addition to its broad, and sudden, achievement. In its lifetime, the open-source portable working framework has developed to incorporate 1.4 billion dynamic clients and 80% of cell phones today run Android programming. ",
  },
  {
    id: "6",
    title: "Fresh Graduate or IT professional Looking for a job ? - 7 reasons to learn Python NOW!",
    category: "Technology and Tools",
    name: "Arman Ahmed",
    dated: "05 Jul 2019",
    img: "https://edyoda.s3.amazonaws.com/media/blog-images/7_reasons_to_learn_Python_u3lFION.jpg",
    desc: "If you are a fresh graduate - or new to IT - looking for the next job, you need to read this. The last couple of years zekeLabs gave me a unique opportunity to assess technology demand in the industry and also to evaluate available talent pool for the demand. Our consulting and technology training assignments for our corporate partners enlightened us on the technology skill in demand. We discovered - What, Where and which technologies are increasingly being adopted by the Industry.",
  },
  {
    id: "7",
    title: "Master your General Aptitude Job Interview Success",
    category: "Get a Job in a Tech Company",
    name: "Pitanjal Dutta",
    dated: "05 Jul 2019",
    img: "https://edyoda.s3.amazonaws.com/media/blog-images/aptitude-small.jpg",
    desc: "A general aptitude becomes very important, when you apply for a job in a tech company. You might be highly skilled in your subject domain. However, these basic aptitude help a recruiter understand your problem solving abilities if something unexpected comes your way during your job role.",
  },
  {
    id: "8",
    title: "Building the University for the 21st century — EdYoda 2.0",
    category: "Others",
    name: "Arman Ahmed",
    dated: "20 Jul 2019",
    img: "https://edyoda.s3.amazonaws.com/media/blog-images/1_G1i7GlRPMGboYZdRhOeWaw.png",
    desc: "The google analytics dashboard was firing up, the whole team, each one of us was on the edges — half elated, half anxious and a little worried. And it happened, the servers crashed due to the surge in traffic. We were clearly not prepared, the number of visitors far exceeded our expectations.",
  },
];

export default Data;